site_name: Satchel Documentation
site_url: https://satchel.luau.page
repo_name: RyanLua/Satchel
repo_url: https://github.com/RyanLua/Satchel

copyright: Copyright &copy; Ryan Luu

theme:
  name: material
  custom_dir: docs/overrides
  features:
    - content.action.edit
    - content.code.copy
    - content.tooltips
    - content.code.annotate
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.tabs
    - search.highlight
    - search.suggest
    - navigation.footer
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
  favicon: assets/favicon.svg
  logo: assets/logo.svg

plugins:
  - search

extra:
  # generator: false
  # version:
  #   provider: mike
  social:
    - icon: simple/github
      link: https://github.com/RyanLua/Satchel
      name: GitHub
    - icon: simple/robloxstudio
      link: https://devforum.roblox.com/t/2451549
      name: DevForum
    - icon: simple/discord
      link: https://discord.gg/N2KEnHzrsW
      name: Discord
  analytics:
    provider: google
    property: PPVP56SBQQ
edit_uri: edit/main/docs/

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - attr_list
  - pymdownx.snippets
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Introduction: introduction.md
  - Installation: installation.md
  - Usage: usage.md
  - Platforms: platforms.md
  - Benchmarks: benchmarks.md
  - Alternatives: alternatives.md
  - API Reference: api-reference.md
