[package]
name = "ryanlua/satchel"
description = "A modern open-source alternative to Roblox's default backpack."
version = "2.0.0"
license = "MPL-2.0"
authors = ["Ryan Luu <ryan.luu@ryanluu.dev>"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
homepage = "https://satchel.luau.page"
repository = "https://github.com/ryanlua/satchel"
exclude = ["**"]
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json", "LICENSE", "README.md"]

[dependencies]
react = "haedrix/react@17.3.8"
react-devtools = "haedrix/react-devtools@17.3.8"
react-globals = "haedrix/react-globals@17.3.8"
react-roblox = "haedrix/react-roblox@17.3.8"
topbarplus = "ryanlua/topbarplus@1.0.1"
