name: Report a bug
description: File a bug report.
labels: ["bug"]
body:
  - type: input
    id: version
    attributes:
      label: Satchel version
      description: What version does your bug occur on?
      placeholder: 1.0.0
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Write a brief sentence about the bug
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: When I do this, that is supposed to happen
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: What actually happened instead? If you have a screenshot or video, attach them.
      placeholder: When I do this, it instead does that
  - type: textarea
    id: repro-steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Any logs from the [Output window](https://create.roblox.com/docs/studio/output) or [Developer Console log](https://create.roblox.com/docs/studio/developer-console#log).
      placeholder: 12:00:00.000  Hello world!  -  Client - Satchel:1
      render: lua
