name: Report a bug
description: File a bug report.
title: "Bug: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this issue!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Write a brief sentence about the bug
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: When I do this, that is supposed to happen
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: What actually happened instead? If you have a screenshot or video, attach them.
      placeholder: When I do this, it instead does that
  - type: textarea
    id: repro-steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output.
      placeholder: Add any relevant log output here. This includes any errors or warnings.
      render: lua
  - type: textarea
    id: other-details
    attributes:
      label: Other details
      description: Is there anything else we should know or have?
      placeholder: The bug is able to be only reproduced able this percent of the time
  - type: input
    id: version
    attributes:
      label: Version
      description: What version does your bug occur on?
      placeholder: 1.0.0
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Low
        - Moderate
        - High
        - Critical
  - type: dropdown
    id: platforms
    attributes:
      label: Platforms affected
      description: What platforms does this bug happen on?
      multiple: true
      options:
        - Computer
        - Tablet
        - Phone
        - Console
        - VR
  - type: dropdown
    id: distribution
    attributes:
      label: Distribution variant
      description: Where did you get Satchel from?
      options:
        - Creator Marketplace
        - Satchel Playground
        - ToolBlocks
        - GitHub
        - Wally
        - Other
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: This project has a Code of Conduct that all participants are expected to understand and follow.
      options:
        - label: I have read and agree to the project's [Code of Conduct](../blob/main/CODE_OF_CONDUCT.md)
          required: true
