blank_issues_enabled: true
contact_links:
  - name: Get community support
    url: https://github.com/RyanLua/Satchel/discussions
    about: Get help from the GitHub Discussions community
  - name: Ask on our Discord server
    url: https://discord.gg/N2KEnHzrsW
    about: Ask members in dedicated channel on our Discord
