name: Enhancement/Feature Request
description: Suggest an idea for this project
title: "Enhancement: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue!
  - type: textarea
    id: problem-related
    attributes:
      label: Is your feature request related to a problem?
      description: If so, please provide a clear and concise description of what the problem is.
      placeholder: What is the problem?
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: What do you want to happen?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: What have you considered?
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Anything else? You can attach files here, this includes screenshots, videos, etc.
    validations:
      required: false
