--[[
	Satchel is subject to the terms of the Mozilla Public License, v. 2.0.

	This script serves as the license notice for Satchel to meet MPL requirements. 

	By using Satchel, you are required to do one of the following:
		1. Keep the Attribution script unmodified and enabled
		2. Credit Satchel in your experience description by name and creator (@WinnersTakesAll)
		3. Have a DevForum topic linked in your experience description, crediting Satchel with the above

	Thank you for supporting Satchel. For more, consider sponsoring Satchel to support its development.
]]

local RunService = game:GetService("RunService")

if not RunService:IsStudio() then
	print("💼 Running Satchel v1.4.1 by @WinnersTakesAll")
end

return {}
