return {
	theme = {
		-- Spacing
		thickness = 5,
		padding = UDim.new(0, 5),
		cornerRadius = UDim.new(0, 8),
		cornerRadiusSmall = UDim.new(0, 3), -- padding - cornerRadius

		-- Font
		font = Enum.Font.BuilderSansMedium,
		fontSmall = Enum.Font.BuilderSansExtraBold,
		textSize = 18,
		textSizeSmall = 14,

		-- Colors
		backgroundColor = Color3.fromRGB(25, 27, 29),
		tooltipBackgroundColor = Color3.fromRGB(38, 40, 48),
		textColor = Color3.fromRGB(255, 255, 255),
		textStrokeColor = Color3.fromRGB(0, 0, 0),
		equippedColor = Color3.fromRGB(255, 255, 255),

		-- Transparency
		backgroundTransparency = 0.3,
		tooltipBackgroundTransparency = 0,
		textStrokeTransparency = 0.5,
	},
}
