return function()
	local Satchel = require(script.Parent)

	it("SetBackpackEnabled(false)", function()
		Satchel:SetBackpackEnabled(false)
		expect(Satchel:GetBackpackEnabled()).to.equal(false)
	end)
	it("SetBackpackEnabled(true)", function()
		Satchel:SetBackpackEnabled(true)
		expect(Satchel:GetBackpackEnabled()).to.equal(true)
	end)
	it("GetBackpackEnabled", function()
		local getBackpackEnabled = Satchel:GetBackpackEnabled()
		expect(getBackpackEnabled).to.be.a("boolean")
	end)
	it("IsOpened", function()
		local isOpened = Satchel:IsOpened()
		expect(isOpened).to.be.a("boolean")
	end)
	it("GetStateChangedEvent", function()
		local getStateChangedEvent = Satchel:GetStateChangedEvent()
		expect(getStateChangedEvent).to.be.a("userdata")
	end)
	it("OpenClose", function()
		local openClose = Satchel.OpenClose
		expect(openClose).to.be.a("function")
	end)
	it("StateChanged", function()
		local stateChanged = Satchel.StateChanged
		expect(stateChanged).to.be.a("userdata")
	end)
	it("BackpackEmpty", function()
		local backpackEmpty = Satchel.BackpackEmpty
		expect(backpackEmpty).to.be.a("userdata")
	end)
	it("BackpackItemAdded", function()
		local backpackItemAdded = Satchel.BackpackItemAdded
		expect(backpackItemAdded).to.be.a("userdata")
	end)
	it("BackpackItemRemoved", function()
		local backpackItemRemoved = Satchel.BackpackItemRemoved
		expect(backpackItemRemoved).to.be.a("userdata")
	end)
end
