name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/docs.yml"
      - "docs/**"
      - "src/**"
      - "mkdocs.yml"

permissions:
  contents: write

env:
  VERSION: 1.x

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - name: Install Material for MkDocs
        run: pip install mkdocs-material mike
      - name: Fetch gh-pages branch
        run: git fetch origin gh-pages --depth=1
      - name: Deploy latest documentation
        run: mike deploy $VERSION --branch gh-pages --push
